// <auto-generated />
using System;
using App.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20250519083810_initt")]
    partial class initt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("App.ApplicationCore.Domain.Chaine", b =>
                {
                    b.Property<int>("ChaineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChaineId"));

                    b.Property<string>("NomChaine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Thematique")
                        .HasColumnType("int");

                    b.HasKey("ChaineId");

                    b.ToTable("Chaines");
                });

            modelBuilder.Entity("App.ApplicationCore.Domain.Programme", b =>
                {
                    b.Property<int>("ProgrammeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgrammeId"));

                    b.Property<string>("Animateur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ChaineId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duree")
                        .HasColumnType("time");

                    b.Property<string>("NomProgramme")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProgrammeId");

                    b.HasIndex("ChaineId");

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("App.ApplicationCore.Domain.Utilisateur", b =>
                {
                    b.Property<int>("UtilisateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilisateurId"));

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomUtilisateur")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UtilisateurId");

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator().HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("App.ApplicationCore.Domain.Visionnage", b =>
                {
                    b.Property<int>("ProgrammeKey")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurKey")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateVisionnage")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Favori")
                        .HasColumnType("bit");

                    b.HasKey("ProgrammeKey", "UtilisateurKey", "DateVisionnage");

                    b.HasIndex("UtilisateurKey");

                    b.ToTable("Visionnages");
                });

            modelBuilder.Entity("App.ApplicationCore.Domain.Premium", b =>
                {
                    b.HasBaseType("App.ApplicationCore.Domain.Utilisateur");

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2");

                    b.Property<int>("PointsFidelite")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Premium");
                });

            modelBuilder.Entity("App.ApplicationCore.Domain.Standard", b =>
                {
                    b.HasBaseType("App.ApplicationCore.Domain.Utilisateur");

                    b.Property<bool>("PubliciteActive")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("Standard");
                });

            modelBuilder.Entity("App.ApplicationCore.Domain.Programme", b =>
                {
                    b.HasOne("App.ApplicationCore.Domain.Chaine", "Chaine")
                        .WithMany("Programmes")
                        .HasForeignKey("ChaineId");

                    b.Navigation("Chaine");
                });

            modelBuilder.Entity("App.ApplicationCore.Domain.Visionnage", b =>
                {
                    b.HasOne("App.ApplicationCore.Domain.Programme", "Programme")
                        .WithMany("Visionnages")
                        .HasForeignKey("ProgrammeKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("App.ApplicationCore.Domain.Utilisateur", "Utilisateur")
                        .WithMany("Visionnages")
                        .HasForeignKey("UtilisateurKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programme");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("App.ApplicationCore.Domain.Chaine", b =>
                {
                    b.Navigation("Programmes");
                });

            modelBuilder.Entity("App.ApplicationCore.Domain.Programme", b =>
                {
                    b.Navigation("Visionnages");
                });

            modelBuilder.Entity("App.ApplicationCore.Domain.Utilisateur", b =>
                {
                    b.Navigation("Visionnages");
                });
#pragma warning restore 612, 618
        }
    }
}
